name: Internship Pro

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Repo Source Code
        uses: actions/checkout@v3

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      #     - name: Push Docker image
      #   run: |
      #     docker tag your_image_name your_dockerhub_username/your_image_name
      #     docker push your_dockerhub_username/your_image_name

      - name: Testing
        run: python manage.py test

      - name: Start Apache Server
        run: |
          sudo apt-get install -y apache2
          sudo service apache2 start

      - name: List contents of internship_product directory
        run: ls -R internship_product
        
      - name: Configure Apache Server
        run: |
          
          sudo cp /home/aditya/internship-pipeline/internship_product/apache/thoughtwin-internship-pro.conf /etc/apache2/sites-available/
          sudo a2ensite thoughtwin-internship-pro.conf
          sudo service apache2 reload


