name: Intenship Pro

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: To Setup Repo Source Code 
      - uses: actions/checkout@v3
      - name: To Setup Python Version
      - uses: actions/checkout@v3
          with: 
            version: python3
      - name: Installing Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Testing............
          run: python3 manage.py test
        
      - name: Deploying..............
          print: Deployed................