name: Internship Pro

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Repo Source Code
        uses: actions/checkout@v3

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      #     - name: Push Docker image
      #   run: |
      #     docker tag your_image_name your_dockerhub_username/your_image_name
      #     docker push your_dockerhub_username/your_image_name

      - name: Testing
        run: python manage.py test

      - name: Set up Apache
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2
          # Configure Apache as per your project requirements

      - name: Copy project files to Apache document root
        run: |
          sudo cp -r * /home/aditya/internship-pipeline/internship_product  # Replace with the appropriate path to your project files

      - name: Restart Apache
        run: sudo systemctl restart apache2

